- name: "Configure EC2 instance in AWS."
  ec2:
    key_name: passcode
    instance_type: t2.micro
    image: ami-0ebc1ac48dfd14136
    wait: yes
    count: 2
    vpc_subnet_id: subnet-fa0075b6
    assign_public_ip: yes
    group_id: sg-0e876941ef6fde568
    region: ap-south-1
    aws_access_key: "{{ access_key }}" 
    aws_secret_key: "{{ secret_key }}"
- name: Refresh Inventory
  meta: refresh_inventory
